# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sdk/v1/telemetry.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'sdk/v1/telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16sdk/v1/telemetry.proto\x12\x0bkaro.sdk.v1\"\xaa\x06\n\x13SdkRobotStateUpdate\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x14\n\x0chealth_score\x18\x02 \x01(\r\x12\x10\n\x08sequence\x18\x03 \x01(\x04\x12\x15\n\rbattery_level\x18\x04 \x01(\r\x12@\n\x0b\x63harge_type\x18\x05 \x01(\x0e\x32+.karo.sdk.v1.SdkRobotStateUpdate.ChargeType\x12\x44\n\rservice_state\x18\x06 \x01(\x0e\x32-.karo.sdk.v1.SdkRobotStateUpdate.ServiceState\x12\x10\n\x08is_estop\x18\x0c \x01(\x08\x12\x13\n\x0bis_hw_estop\x18\x1a \x01(\x08\x12\x13\n\x0bis_sw_estop\x18\x1b \x01(\x08\x12\x0e\n\x06\x65rrors\x18\r \x03(\r\x12\x15\n\ractive_map_id\x18\x0e \x01(\t\x12\x17\n\x0f\x61\x63tive_map_name\x18\x0f \x01(\t\x12\x14\n\x0c\x61\x63tive_floor\x18\x10 \x01(\x05\x12\x17\n\x0f\x63urrent_task_id\x18\x12 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x17 \x01(\x04\x12\x14\n\x0cidle_seconds\x18\x18 \x01(\x04\x12\x18\n\x10\x63harging_seconds\x18\x19 \x01(\x04\"N\n\nChargeType\x12\x14\n\x10\x43HARGE_TYPE_NONE\x10\x00\x12\x14\n\x10\x43HARGE_TYPE_WIRE\x10\x01\x12\x14\n\x10\x43HARGE_TYPE_DOCK\x10\x02\"\xf6\x01\n\x0cServiceState\x12\x16\n\x12SERVICE_STATE_IDLE\x10\x00\x12\x16\n\x12SERVICE_STATE_TASK\x10\x01\x12\x19\n\x15SERVICE_STATE_MAPPING\x10\x02\x12\x1a\n\x16SERVICE_STATE_STARTING\x10\x03\x12\x1f\n\x1bSERVICE_STATE_SHUTTING_DOWN\x10\x04\x12\x1b\n\x17SERVICE_STATE_UPGRADING\x10\x05\x12 \n\x1cSERVICE_STATE_REMOTE_CONTROL\x10\x06\x12\x1f\n\x1bSERVICE_STATE_GOTO_CHARGING\x10\x07\x42@Z>github.com/Kanesir-Developer/karo-x2-sdk-go/proto/sdk/v1;sdkv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sdk.v1.telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/Kanesir-Developer/karo-x2-sdk-go/proto/sdk/v1;sdkv1'
  _globals['_SDKROBOTSTATEUPDATE']._serialized_start=40
  _globals['_SDKROBOTSTATEUPDATE']._serialized_end=850
  _globals['_SDKROBOTSTATEUPDATE_CHARGETYPE']._serialized_start=523
  _globals['_SDKROBOTSTATEUPDATE_CHARGETYPE']._serialized_end=601
  _globals['_SDKROBOTSTATEUPDATE_SERVICESTATE']._serialized_start=604
  _globals['_SDKROBOTSTATEUPDATE_SERVICESTATE']._serialized_end=850
# @@protoc_insertion_point(module_scope)
