# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: karo/v1/control.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'karo/v1/control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from karo.v1 import common_pb2 as karo_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15karo/v1/control.proto\x12\x07karo.v1\x1a\x14karo/v1/common.proto\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"L\n\x05Twist\x12 \n\x06linear\x18\x01 \x01(\x0b\x32\x10.karo.v1.Vector3\x12!\n\x07\x61ngular\x18\x02 \x01(\x0b\x32\x10.karo.v1.Vector3\"V\n\rCmdVelRequest\x12\x1d\n\x05twist\x18\x01 \x01(\x0b\x32\x0e.karo.v1.Twist\x12\x10\n\x08sequence\x18\x02 \x01(\x04\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x04\"?\n\x0e\x43mdVelResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x1b\n\x13\x64\x65vice_timestamp_ms\x18\x02 \x01(\x04\x32h\n\x0e\x43ontrolService\x12V\n\x06\x43mdVel\x12\x16.karo.v1.CmdVelRequest\x1a\x17.karo.v1.CmdVelResponse\"\x1b\x80\xb5\x18\x01\x8a\xb5\x18\x0f\x63ontrol.cmd_vel\x90\xb5\x18\x01\x42\x61\n\x1b\x63om.kanesir.karo.sdk.gen.v1P\x01Z@github.com/Kanesir-Developer/karo-x2-sdk-go/proto/karo/v1;karov1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'karo.v1.control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.kanesir.karo.sdk.gen.v1P\001Z@github.com/Kanesir-Developer/karo-x2-sdk-go/proto/karo/v1;karov1'
  _globals['_CONTROLSERVICE'].methods_by_name['CmdVel']._loaded_options = None
  _globals['_CONTROLSERVICE'].methods_by_name['CmdVel']._serialized_options = b'\200\265\030\001\212\265\030\017control.cmd_vel\220\265\030\001'
  _globals['_VECTOR3']._serialized_start=56
  _globals['_VECTOR3']._serialized_end=98
  _globals['_TWIST']._serialized_start=100
  _globals['_TWIST']._serialized_end=176
  _globals['_CMDVELREQUEST']._serialized_start=178
  _globals['_CMDVELREQUEST']._serialized_end=264
  _globals['_CMDVELRESPONSE']._serialized_start=266
  _globals['_CMDVELRESPONSE']._serialized_end=329
  _globals['_CONTROLSERVICE']._serialized_start=331
  _globals['_CONTROLSERVICE']._serialized_end=435
# @@protoc_insertion_point(module_scope)
