# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: karo/v1/move.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'karo/v1/move.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from karo.v1 import common_pb2 as karo_dot_v1_dot_common__pb2
from karo.v1 import tasks_pb2 as karo_dot_v1_dot_tasks__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12karo/v1/move.proto\x12\x07karo.v1\x1a\x14karo/v1/common.proto\x1a\x13karo/v1/tasks.proto\"1\n\nPoseTarget\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\r\n\x05theta\x18\x03 \x01(\x01\"x\n\x15\x43reateMoveTaskRequest\x12\x13\n\tmarker_id\x18\x01 \x01(\tH\x00\x12#\n\x04pose\x18\x03 \x01(\x0b\x32\x13.karo.v1.PoseTargetH\x00\x12\x1b\n\x13\x63lient_timestamp_ms\x18\x02 \x01(\x04\x42\x08\n\x06target\"5\n\x16\x43reateMoveTaskResponse\x12\x1b\n\x04task\x18\x01 \x01(\x0b\x32\r.karo.v1.Task2~\n\x0bMoveService\x12o\n\nCreateTask\x12\x1e.karo.v1.CreateMoveTaskRequest\x1a\x1f.karo.v1.CreateMoveTaskResponse\" \x80\xb5\x18\x01\x8a\xb5\x18\x10move.create_task\x90\xb5\x18\x01\x98\xb5\x18\x00\x42\x61\n\x1b\x63om.kanesir.karo.sdk.gen.v1P\x01Z@github.com/Kanesir-Developer/karo-x2-sdk-go/proto/karo/v1;karov1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'karo.v1.move_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.kanesir.karo.sdk.gen.v1P\001Z@github.com/Kanesir-Developer/karo-x2-sdk-go/proto/karo/v1;karov1'
  _globals['_MOVESERVICE'].methods_by_name['CreateTask']._loaded_options = None
  _globals['_MOVESERVICE'].methods_by_name['CreateTask']._serialized_options = b'\200\265\030\001\212\265\030\020move.create_task\220\265\030\001\230\265\030\000'
  _globals['_POSETARGET']._serialized_start=74
  _globals['_POSETARGET']._serialized_end=123
  _globals['_CREATEMOVETASKREQUEST']._serialized_start=125
  _globals['_CREATEMOVETASKREQUEST']._serialized_end=245
  _globals['_CREATEMOVETASKRESPONSE']._serialized_start=247
  _globals['_CREATEMOVETASKRESPONSE']._serialized_end=300
  _globals['_MOVESERVICE']._serialized_start=302
  _globals['_MOVESERVICE']._serialized_end=428
# @@protoc_insertion_point(module_scope)
