# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: karo/v1/safety.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'karo/v1/safety.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from karo.v1 import common_pb2 as karo_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14karo/v1/safety.proto\x12\x07karo.v1\x1a\x14karo/v1/common.proto\"(\n\x14\x45mergencyStopRequest\x12\x10\n\x08\x61\x63tivate\x18\x01 \x01(\x08\">\n\x15\x45mergencyStopResponse\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x04\x12\x0f\n\x07stopped\x18\x02 \x01(\x08\x32\x86\x01\n\rSafetyService\x12u\n\rEmergencyStop\x12\x1d.karo.v1.EmergencyStopRequest\x1a\x1e.karo.v1.EmergencyStopResponse\"%\x80\xb5\x18\x01\x8a\xb5\x18\x15safety.emergency_stop\x90\xb5\x18\x01\x98\xb5\x18\x01\x42\x61\n\x1b\x63om.kanesir.karo.sdk.gen.v1P\x01Z@github.com/Kanesir-Developer/karo-x2-sdk-go/proto/karo/v1;karov1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'karo.v1.safety_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.kanesir.karo.sdk.gen.v1P\001Z@github.com/Kanesir-Developer/karo-x2-sdk-go/proto/karo/v1;karov1'
  _globals['_SAFETYSERVICE'].methods_by_name['EmergencyStop']._loaded_options = None
  _globals['_SAFETYSERVICE'].methods_by_name['EmergencyStop']._serialized_options = b'\200\265\030\001\212\265\030\025safety.emergency_stop\220\265\030\001\230\265\030\001'
  _globals['_EMERGENCYSTOPREQUEST']._serialized_start=55
  _globals['_EMERGENCYSTOPREQUEST']._serialized_end=95
  _globals['_EMERGENCYSTOPRESPONSE']._serialized_start=97
  _globals['_EMERGENCYSTOPRESPONSE']._serialized_end=159
  _globals['_SAFETYSERVICE']._serialized_start=162
  _globals['_SAFETYSERVICE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
