# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: karo/v1/stream.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'karo/v1/stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from karo.v1 import common_pb2 as karo_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14karo/v1/stream.proto\x12\x07karo.v1\x1a\x14karo/v1/common.proto\"\xe2\x01\n\x0bStreamEvent\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0b\n\x03seq\x18\x02 \x01(\x04\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12\x34\n\x08metadata\x18\x05 \x03(\x0b\x32\".karo.v1.StreamEvent.MetadataEntry\x12)\n\x0bserver_tier\x18\x06 \x01(\x0e\x32\x14.karo.v1.QualityTier\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xbb\x01\n\tSubscribe\x12\x0e\n\x06topics\x18\x01 \x03(\t\x12\x1e\n\x03qos\x18\x02 \x01(\x0e\x32\x11.karo.v1.QosClass\x12\x11\n\tsince_seq\x18\x03 \x01(\x04\x12\x15\n\rhistory_limit\x18\x04 \x01(\r\x12&\n\x08max_tier\x18\x05 \x01(\x0e\x32\x14.karo.v1.QualityTier\x12,\n\x0epreferred_tier\x18\x06 \x01(\x0e\x32\x14.karo.v1.QualityTier\"\x1d\n\x0bUnsubscribe\x12\x0e\n\x06topics\x18\x01 \x03(\t\"s\n\x0cSubscribeAck\x12\x17\n\x0ftopics_accepted\x18\x01 \x03(\t\x12\x17\n\x0ftopics_rejected\x18\x02 \x03(\t\x12 \n\x04\x63ode\x18\x03 \x01(\x0e\x32\x12.karo.v1.ErrorCode\x12\x0f\n\x07message\x18\x04 \x01(\t\"\xb2\x01\n\nPoseUpdate\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\n\n\x02qx\x18\x04 \x01(\x01\x12\n\n\x02qy\x18\x05 \x01(\x01\x12\n\n\x02qz\x18\x06 \x01(\x01\x12\n\n\x02qw\x18\x07 \x01(\x01\x12\n\n\x02vx\x18\x08 \x01(\x01\x12\n\n\x02vy\x18\t \x01(\x01\x12\n\n\x02wz\x18\n \x01(\x01\x12\x0e\n\x06\x63ov_xx\x18\x0b \x01(\x01\x12\x0e\n\x06\x63ov_yy\x18\x0c \x01(\x01\x12\x0f\n\x07\x63ov_yaw\x18\r \x01(\x01\x42\x61\n\x1b\x63om.kanesir.karo.sdk.gen.v1P\x01Z@github.com/Kanesir-Developer/karo-x2-sdk-go/proto/karo/v1;karov1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'karo.v1.stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.kanesir.karo.sdk.gen.v1P\001Z@github.com/Kanesir-Developer/karo-x2-sdk-go/proto/karo/v1;karov1'
  _globals['_STREAMEVENT_METADATAENTRY']._loaded_options = None
  _globals['_STREAMEVENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_STREAMEVENT']._serialized_start=56
  _globals['_STREAMEVENT']._serialized_end=282
  _globals['_STREAMEVENT_METADATAENTRY']._serialized_start=235
  _globals['_STREAMEVENT_METADATAENTRY']._serialized_end=282
  _globals['_SUBSCRIBE']._serialized_start=285
  _globals['_SUBSCRIBE']._serialized_end=472
  _globals['_UNSUBSCRIBE']._serialized_start=474
  _globals['_UNSUBSCRIBE']._serialized_end=503
  _globals['_SUBSCRIBEACK']._serialized_start=505
  _globals['_SUBSCRIBEACK']._serialized_end=620
  _globals['_POSEUPDATE']._serialized_start=623
  _globals['_POSEUPDATE']._serialized_end=801
# @@protoc_insertion_point(module_scope)
