# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: karo/v1/transport.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'karo/v1/transport.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from karo.v1 import rpc_pb2 as karo_dot_v1_dot_rpc__pb2
from karo.v1 import stream_pb2 as karo_dot_v1_dot_stream__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17karo/v1/transport.proto\x12\x07karo.v1\x1a\x11karo/v1/rpc.proto\x1a\x14karo/v1/stream.proto\"\xbe\x02\n\x0eTransportFrame\x12#\n\x07request\x18\x01 \x01(\x0b\x32\x10.karo.v1.RequestH\x00\x12%\n\x08response\x18\x02 \x01(\x0b\x32\x11.karo.v1.ResponseH\x00\x12,\n\x0cstream_event\x18\x03 \x01(\x0b\x32\x14.karo.v1.StreamEventH\x00\x12\'\n\tsubscribe\x18\x04 \x01(\x0b\x32\x12.karo.v1.SubscribeH\x00\x12+\n\x0bunsubscribe\x18\x05 \x01(\x0b\x32\x14.karo.v1.UnsubscribeH\x00\x12.\n\rsubscribe_ack\x18\x06 \x01(\x0b\x32\x15.karo.v1.SubscribeAckH\x00\x12\x16\n\tsender_id\x18\x07 \x01(\rH\x01\x88\x01\x01\x42\x06\n\x04\x62odyB\x0c\n\n_sender_idBa\n\x1b\x63om.kanesir.karo.sdk.gen.v1P\x01Z@github.com/Kanesir-Developer/karo-x2-sdk-go/proto/karo/v1;karov1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'karo.v1.transport_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.kanesir.karo.sdk.gen.v1P\001Z@github.com/Kanesir-Developer/karo-x2-sdk-go/proto/karo/v1;karov1'
  _globals['_TRANSPORTFRAME']._serialized_start=78
  _globals['_TRANSPORTFRAME']._serialized_end=396
# @@protoc_insertion_point(module_scope)
